pipeline {
  agent any
  environment
  {
	PATH="/opt/gradle/gradle-6.4.1/bin:${PATH}"
  }
  stages {
    stage('Source') {
      steps {
        git branch: 'main', changelog: false, poll: false, url: 'https://github.com/vsagar100/devops-jenkins-gradle-arti.git'
      }
    }
    stage('Compile') {
	steps{
		withGradle()
		{
			sh 'gradle -v'
		}
      sh 'gradle clean compileJava test'
      }
    }
    stage('Deploy to Tomcat')
    {
	steps
	{
		sshagent(['deploy_tomcat_user'])
		{
			sh "scp -o StrictHostKeyChecking=no webapp/target/webapp.war azureuser@ltom00ea.eastasia.cloudapp.azure.com:/usr/local/tomcat9/webapps"
		}
	}
    }
  }//stages
}
